import type { Metadata } from "next";
import { Open_Sans } from 'next/font/google';
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const openSans = Open_Sans({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
  variable: '--font-open-sans',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "VRent",
  description: "Generated by VRent",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${openSans.variable} bg-white text-black`}
      >
        <div className="relative w-full overflow-x-hidden">
          <Header />
          <div className="relative bg-white text-black w-full p-5 md:p-10 xl:p-20 min-h-screen">
          {children}
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
