import type { Metadata } from "next";
import { Playfair_Display } from 'next/font/google';
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const playfair = Playfair_Display({
  subsets: ['latin'],
  weight: ['400', '700'], // Add other weights if needed
  display: 'swap',
});

export const metadata: Metadata = {
  title: "VRent",
  description: "Generated by VRent",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${playfair.className} bg-white text-black`}
      >
        {children}
      </body>
    </html>
  );
}
